Algoritmo "semnome"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/05/2021
Var
   nome : caractere
   idade: inteiro


Inicio
   escreval ("Qual é seu nome? ")
   leia (nome)
   limpatela
   escreval ("Qual é sua idade? ")
   leia (idade)
   limpatela
   se idade > 18 entao
      escreval ("MAIOR DE IDADE !")
   senao
      escreval ("MENOR DE IDADE")
   fimse

Fimalgoritmo